# Generated by Django 5.1 on 2024-08-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamMembers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='name',
            new_name='firstName',
        ),
        migrations.AddField(
            model_name='teammember',
            name='lastName',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
